/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

//Define variables
var x = 0;
var y = 1;
var sum = 0;
var temp;
//Run while loop with nested if to check and add to sum if modulus checks out
   while(x <= 4e6){
       temp = x + y;
       x = y;
       y = temp;
       if(x % 2 === 0){
           sum += x;
       }
   }
console.log(sum); //spit out big number, which should be 4613732
